### ISSUE TITLE
Test suite build failure

### ISSUE THREAD

**Issue by snoyberg** [qnikst/binary-conduit#11] opened 2017-07-31 08:56 UTC
```
[1 of 1] Compiling Main             ( test/Main.hs, dist/build/test-binary-conduit/test-binary-conduit-tmp/Main.o )

test/Main.hs:89:19: error:
    • Could not deduce (Testable a0) arising from a use of ‘monadicIO’
      from the context: (Binary a, Eq a)
        bound by the type signature for:
                   prop_eq_plus :: forall a. (Binary a, Eq a) => [a] -> Property
        at test/Main.hs:88:1-51
      The type variable ‘a0’ is ambiguous
      These potential instances exist:
        instance [safe] Testable prop => Testable (Gen prop)
          -- Defined in ‘Test.QuickCheck.Property’
        instance [safe] Testable Discard
          -- Defined in ‘Test.QuickCheck.Property’
        instance [safe] Testable Prop
          -- Defined in ‘Test.QuickCheck.Property’
        ...plus six others
        (use -fprint-potential-instances to see them all)
```

**Comment by qnikst** [comment] 2017-07-31 21:08
Thanks for the report. Please can you add some information about how to reproduce this error, some special GHC version or stackage snapshot?
I was unable to reproduce it locally. I've added new set of travis builds to see if it will catch the problem, but some explicit reply will be helpful. Thanks!

**Comment by snoyberg** [comment] 2017-08-01 03:26
This occurred during a Stackage build, using GHC 8.2 and QuickCheck 2.10. I'm almost certain the latter is what caused this.

**Comment by qnikst** [comment] 2017-08-02 08:43
Thanks for the report and suggestion! I've fixed in and I have uploaded new version http://hackage.haskell.org/package/binary-conduit-1.2.5 .

**Closed by qnikst** 2017-08-02 08:43 UTC
